# Generated by Django 2.1.7 on 2019-04-04 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('attended', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StudentsDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('dateofbirth', models.DateField()),
                ('address', models.TextField(default='')),
                ('placeofbirth', models.CharField(max_length=100)),
                ('phnum', models.IntegerField(default=0)),
                ('emailid', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.CharField(choices=[('F', 'F'), ('M', 'M')], max_length=1)),
                ('fathername', models.CharField(max_length=100)),
                ('mothername', models.CharField(max_length=100)),
                ('fatherprofession', models.CharField(max_length=100)),
                ('motherprofession', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='attendence',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.StudentsDB'),
        ),
    ]
