# Generated by Django 2.1.7 on 2019-04-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20190406_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formid', models.CharField(max_length=12)),
                ('classnumber', models.IntegerField()),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('F', 'F'), ('M', 'M')], max_length=1)),
                ('dateofbirth', models.DateField()),
                ('placeofbirth', models.CharField(max_length=100)),
                ('address', models.TextField(default='')),
                ('phnum', models.IntegerField(default=0)),
                ('emailid', models.CharField(blank=True, max_length=100, null=True)),
                ('fathername', models.CharField(max_length=100)),
                ('mothername', models.CharField(max_length=100)),
                ('fatherprofession', models.CharField(max_length=100)),
                ('motherprofession', models.CharField(max_length=100)),
                ('lastschool', models.CharField(max_length=100)),
                ('lastclassmarks', models.CharField(max_length=7)),
            ],
        ),
    ]
