# Generated by Django 2.1.7 on 2019-04-09 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgmnt', '0004_orginfo_shortcode'),
        ('students', '0003_admissionform'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsdb',
            name='orginfo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mgmnt.Orginfo'),
            preserve_default=False,
        ),
    ]
