# Generated by Django 2.1.7 on 2019-04-09 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgmnt', '0004_orginfo_shortcode'),
        ('students', '0004_studentsdb_orginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionform',
            name='orginfo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mgmnt.Orginfo'),
            preserve_default=False,
        ),
    ]
