# Generated by Django 2.1.7 on 2019-04-09 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_admissionform_orginfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsdb',
            name='orginfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mgmnt.Orginfo'),
        ),
    ]
