# Generated by Django 2.1.7 on 2019-04-10 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0001_initial'),
        ('students', '0006_auto_20190409_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsdb',
            name='classno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Academic.Classes'),
        ),
    ]
