# Generated by Django 2.1.7 on 2019-04-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_studentsdb_classno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionform',
            name='middlename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentsdb',
            name='middlename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
