# Generated by Django 2.1.7 on 2019-04-13 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgmnt', '0006_remove_userextension_image'),
        ('students', '0008_auto_20190410_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsdb',
            name='userext',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mgmnt.userextension'),
        ),
    ]
