# Generated by Django 2.1.7 on 2019-04-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_studentsdb_userext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsdb',
            name='middlename',
            field=models.CharField(default='', max_length=100),
        ),
    ]
