# Generated by Django 2.1.7 on 2019-04-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_auto_20190413_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
