# Generated by Django 2.1.7 on 2019-04-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20190413_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsdb',
            name='simage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
