# Generated by Django 2.1.7 on 2019-04-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_auto_20190414_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsdb',
            name='simage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
