# Generated by Django 2.1.7 on 2019-04-14 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_auto_20190414_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsdb',
            name='simage',
        ),
    ]
