# Generated by Django 2.1.7 on 2019-04-06 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employeeDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('F', 'F'), ('M', 'M')], max_length=1)),
                ('dateofbirth', models.DateField()),
                ('placeofbirth', models.CharField(max_length=100)),
                ('address', models.TextField(default='')),
                ('phnum', models.IntegerField(default=0)),
                ('emailid', models.CharField(blank=True, max_length=100, null=True)),
                ('fathername', models.CharField(max_length=100)),
                ('mothername', models.CharField(max_length=100)),
                ('fatherprofession', models.CharField(max_length=100)),
                ('motherprofession', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employeetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeework', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='employeedb',
            name='employeetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.Employeetype'),
        ),
    ]
