# Generated by Django 2.1.7 on 2019-04-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20190410_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedb',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
