# Generated by Django 2.1.7 on 2019-04-13 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgmnt', '0006_remove_userextension_image'),
        ('employee', '0003_employeedb_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedb',
            name='userext',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mgmnt.userextension'),
        ),
    ]
