# Generated by Django 2.1.7 on 2019-04-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_employeedb_employeetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedb',
            name='middlename',
            field=models.CharField(default='', max_length=100),
        ),
    ]
