# Generated by Django 2.1.7 on 2019-04-10 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classid', models.IntegerField()),
                ('section', models.CharField(max_length=2)),
                ('classteacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.employeeDB')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.Classes')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.employeeDB')),
            ],
        ),
    ]
