# Generated by Django 2.1.7 on 2019-04-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='subjectname',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjects',
            name='subjecttype',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Aditional', 'Aditional')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
