# Generated by Django 2.1.7 on 2019-04-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0002_auto_20190410_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
            ],
        ),
    ]
