# Generated by Django 2.1.7 on 2019-04-10 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0004_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='periodnumber',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Academic.Periods'),
            preserve_default=False,
        ),
    ]
