# Generated by Django 2.1.7 on 2019-04-04 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mgmnt', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='aaauserdb',
        ),
        migrations.DeleteModel(
            name='Alertsdb',
        ),
    ]
