# Generated by Django 2.1.7 on 2019-04-09 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgmnt', '0002_auto_20190404_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextension',
            name='Utype',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default='user', max_length=10),
        ),
        migrations.AddField(
            model_name='userextension',
            name='orginfo',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='mgmnt.Orginfo'),
            preserve_default=False,
        ),
    ]
