# Generated by Django 2.1.7 on 2019-04-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmnt', '0003_auto_20190409_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='orginfo',
            name='shortcode',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
