# Generated by Django 2.1.7 on 2019-04-13 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mgmnt', '0004_orginfo_shortcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextension',
            name='Utype',
        ),
        migrations.RemoveField(
            model_name='userextension',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userextension',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userextension',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='userextension',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userextension',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userextension',
            name='website',
        ),
    ]
