# Generated by Django 2.1.7 on 2019-04-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmnt', '0006_remove_userextension_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextension',
            name='utype',
            field=models.CharField(default='employee', max_length=10),
        ),
    ]
